# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5359668641ff9de7e2308270fa98982bf193e04a79af554dda6d7a779e0ca6e492fc33680519972b60b1828f274812cd298f3ea3fd3244ec070dcb4f736e17d7

test:
  secret_key_base: a71a1eaf79d81ebd11fd1f472e407734a573786bad939948696617505cc60510a32b803a94dabab54b866d537c96b2f4999ea69bc4cc28935d9f6b24700d203a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
